SENSOR_EXTRINSIC = {
    imu_extrinsic = {
        frame_id = "imu",
        trans_x = 0.,
        trans_y = 0.,
        trans_z = 0.,
        rotat_w = 1.,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = 0.,
    },
    odom_extrinsic = {
        frame_id = "odom",
        trans_x = 0.,
        trans_y = 0.,
        trans_z = 0.,
        rotat_w = 1.,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = 0.,
    },
    scan_1_extrinsic = {
        frame_id = "scan_1",
        trans_x = 0.3787,
        trans_y = -0.2477,
        trans_z = 0.,
        rotat_w = 0.923879,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = -0.382683,
    },
    scan_2_extrinsic = {
        frame_id = "scan_2",
        trans_x = -0.3895,
        trans_y = 0.2547,
        trans_z = 0.,
        rotat_w = 0.382683,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = 0.923880,
    },
    camera_1_extrinsic = {
        frame_id = "camera_1",
        trans_x = 0.,
        trans_y = 0.,
        trans_z = 0.,
        rotat_w = 1.,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = 0.,
    },
}
