SENSOR_EXTRINSIC = {
    imu_extrinsic = {
        frame_id = "imu",
        trans_x = 0.,
        trans_y = 0.,
        trans_z = 0.,
        rotat_w = 1.,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = 0.,
    },
    odom_extrinsic = {
        frame_id = "odom",
        trans_x = 0.,
        trans_y = 0.,
        trans_z = 0.,
        rotat_w = 1.,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = 0.,
    },
    scan_1_extrinsic = {
        frame_id = "scan_1",
        trans_x = 0.567700,
        trans_y = -0.387550,
        trans_z = 0.,
        rotat_w = 0.923880,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = -0.382683,
    },
    scan_2_extrinsic = {
        frame_id = "scan_2",
        trans_x = -0.195975,
        trans_y = 0.121567,
        trans_z = 0.,
        rotat_w = -0.382683,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = -0.923880,
    },
    camera_1_extrinsic = {
        frame_id = "camera_1",
        trans_x = 0.,
        trans_y = 0.,
        trans_z = 0.,
        rotat_w = 1.,
        rotat_x = 0.,
        rotat_y = 0.,
        rotat_z = 0.,
    },
}
